---

- name: Install with apt
  apt:
    name: kibana
    update_cache: yes

- name: Updating the config file
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host'
    line: 'server.host: 0.0.0.0'

- name: defining server port
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.port:'
    line: 'server.port: 5601'

- name: defining elasticsearch url
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'elasticsearch.url:'
    line: 'elasticsearch.url: "http://localhost:9200"'

- name: starting kibana
  service:
    name: kibana
    state: started
